In [13]:
import numpy as np
import pandas as pd

In [14]:
file_path = "../reports/evaluation_results.csv"
df = pd.read_csv(file_path)

In [15]:
df.head()

,id,model_name,path,repetition,backbone,downstream,cap,iou,f1
0,4dc1e6d190c9c326d9e0bea1d982b8f3,V1_pre_f3_train_f3_cap_1%,../saves/models/V1/V1_pre_f3_train_f3_cap_1%,V1,f3,f3,0.01,0.523991,0.842487
1,e927307a871f4c301682130330a109a3,V1_pre_f3_train_f3_cap_10%,../saves/models/V1/V1_pre_f3_train_f3_cap_10%,V1,f3,f3,0.10,0.647739,0.882627
2,7d63cad218addf0471564e65c5ba886e,V1_pre_f3_train_f3_cap_50%,../saves/models/V1/V1_pre_f3_train_f3_cap_50%,V1,f3,f3,0.50,0.707516,0.900241
3,244607e5324ff0e134bc031092156201,V1_pre_f3_train_f3_cap_100%,../saves/models/V1/V1_pre_f3_train_f3_cap_100%,V1,f3,f3,1.00,0.716942,0.901039
4,069c79b3d5744183eb7b6df084714717,V1_pre_f3_train_f3_N_cap_1%,../saves/models/V1/V1_pre_f3_train_f3_N_cap_1%,V1,f3,f3_N,0.01,0.542652,0.847796

In [16]:
grouped = df.groupby(["downstream", "cap", "backbone"])['iou'].agg(['mean', 'std']).reset_index()
grouped

    downstream   cap      backbone      mean       std
0           f3  0.01          COCO  0.474724  0.040607
1           f3  0.01      IMAGENET  0.427780  0.050945
2           f3  0.01          both  0.496917  0.038309
3           f3  0.01        both_N  0.456837  0.066536
4           f3  0.01            f3  0.562326  0.048399
..         ...   ...           ...       ...       ...
155  seam_ai_N  1.00       f3_norm  0.717204  0.018639
156  seam_ai_N  1.00       seam_ai  0.720010  0.019058
157  seam_ai_N  1.00  seam_ai_norm  0.716771  0.010741
158  seam_ai_N  1.00           seg  0.677086  0.017174
159  seam_ai_N  1.00           sup  0.717375  0.018762

[160 rows x 5 columns]

In [17]:
grouped['backbone'].unique()

array(['COCO', 'IMAGENET', 'both', 'both_N', 'f3', 'f3_norm', 'seam_ai',
       'seam_ai_norm', 'seg', 'sup'], dtype=object)

In [18]:
grouped.replace({
    "seam_ai_norm": "seam_ai_N",
    "IMAGENET": "imagenet",
    "COCO": "coco",
    "f3_norm": "f3_N"
}, inplace=True)

In [ ]:
grouped.rename(columns={"backbone": "pretrain_data", "downstream": "train_data"}, inplace=True)
grouped['cap'] = (grouped['cap'] * 100).astype(float)
grouped['cap'].unique()

array([  1.,  10.,  50., 100.])

In [20]:
grouped.to_csv("grouped.csv", index=False)